[project]
name = "appliedcrypto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cryptography>=46.0.3",
    "pqcrypto>=0.3.4",
]
